export const UPDATE_QUIZ_STARTED = 'UPDATE_QUIZ_STARTED';
export type UPDATE_QUIZ_STARTED = typeof UPDATE_QUIZ_STARTED;

export const UPDATE_QUIZ_OPTION = 'UPDATE_QUIZ_OPTION';
export type UPDATE_QUIZ_OPTION = typeof UPDATE_QUIZ_OPTION;

export const LOAD_QUESTION_LIST = 'LOAD_QUESTION_LIST';
export type LOAD_QUESTION_LIST = typeof LOAD_QUESTION_LIST;

export const ADD_ANSWERED_QUESTION_TO_LIST = 'ADD_ANSWERED_QUESTION_TO_LIST';
export type ADD_ANSWERED_QUESTION_TO_LIST = typeof ADD_ANSWERED_QUESTION_TO_LIST;

export const UPDATE_ANSWERED_QUESTION_TO_LIST = 'UPDATE_ANSWERED_QUESTION_TO_LIST';
export type UPDATE_ANSWERED_QUESTION_TO_LIST = typeof UPDATE_ANSWERED_QUESTION_TO_LIST;

export const DELETE_ANSWERED_QUESTION_FROM_LIST = 'DELETE_ANSWERED_QUESTION_FROM_LIST';
export type DELETE_ANSWERED_QUESTION_FROM_LIST = typeof DELETE_ANSWERED_QUESTION_FROM_LIST;

export const UPDATE_CURRENT_QUESTION_NUMBER = 'UPDATE_CURRENT_QUESTION_NUMBER';
export type UPDATE_CURRENT_QUESTION_NUMBER = typeof UPDATE_CURRENT_QUESTION_NUMBER;

export const UPDATE_MAX_QIESTION_NUMBER = 'UPDATE_MAX_QIESTION_NUMBER';
export type UPDATE_MAX_QIESTION_NUMBER = typeof UPDATE_MAX_QIESTION_NUMBER;

export const UPDATE_CURRENT_ANSWER = 'UPDATE_CURRENT_ANSWER';
export type UPDATE_CURRENT_ANSWER = typeof UPDATE_CURRENT_ANSWER;

export const UPDATE_PROGRESS_COUNTER = 'UPDATE_PROGRESS_COUNTER';
export type UPDATE_PROGRESS_COUNTER = typeof UPDATE_PROGRESS_COUNTER;

export const UPDATE_CORRECT_ANSWER_COUNTER = 'UPDATE_CORRECT_ANSWER_COUNTER';
export type UPDATE_CORRECT_ANSWER_COUNTER = typeof UPDATE_CORRECT_ANSWER_COUNTER;

export const UPDATE_CURRENT_ANSWER_SUBMITTED = 'UPDATE_CURRENT_ANSWER_SUBMITTED';
export type UPDATE_CURRENT_ANSWER_SUBMITTED = typeof UPDATE_CURRENT_ANSWER_SUBMITTED;

export const UPDATE_TOTAL_QUESTIONS = 'UPDATE_TOTAL_QUESTIONS';
export type UPDATE_TOTAL_QUESTIONS = typeof UPDATE_TOTAL_QUESTIONS;

export const UPDATE_QUESTION_ORDER = 'UPDATE_QUESTION_ORDER';
export type UPDATE_QUESTION_ORDER = typeof UPDATE_QUESTION_ORDER;

export const UPDATE_RANDOMISE_QUESTION = 'UPDATE_RANDOMISE_QUESTION';
export type UPDATE_RANDOMISE_QUESTION = typeof UPDATE_RANDOMISE_QUESTION;

export const UPDATE_PRACTICE_MODE = 'UPDATE_PRACTICE_MODE';
export type UPDATE_PRACTICE_MODE = typeof UPDATE_PRACTICE_MODE;

export const UPDATE_FETCHING = 'UPDATE_FETCHING';
export type UPDATE_FETCHING = typeof UPDATE_FETCHING;

export const UPDATE_FETCHING_SUCCESS = 'UPDATE_FETCHING_SUCCESS';
export type UPDATE_FETCHING_SUCCESS = typeof UPDATE_FETCHING_SUCCESS;

export const UPDATE_QUIZ_COMPLETED = 'UPDATE_QUIZ_COMPLETED';
export type UPDATE_QUIZ_COMPLETED = typeof UPDATE_QUIZ_COMPLETED;

export const START_AGAIN = 'START_AGAIN';
export type START_AGAIN = typeof START_AGAIN;